<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Client1.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
       <div class="container">        
        <ul id="discussion">
        </ul>
    </div>

     <script src="Scripts/jquery-1.6.4.min.js"></script> 
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>  
   <%-- <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.7/signalr.min.js"></script>--%>
    <!--Reference the autogenerated SignalR hub script. -->
        
 
    <script type="text/javascript">

        $.getScript('https://localhost:44371/signalr/hubs', function () {
            //Set the hubs URL for the connection
            $.connection.hub.url = 'https://localhost:44371/signalr';
            var hub = $.connection.chatHub; //yourHub is name of hub on the server side
            console.log(hub);
            //wire up SignalR

            hub.client.broadcastMessage = function (name, message) {  
                $('#discussion').append('<li><strong>' + name
                    + '</strong>:&nbsp;&nbsp;' + message + '</li>');
            };

            //start hub
            $.connection.hub.start().done(function () {
                //once we're done with SignalR init we can wire up our other stuff
            });
        });
    
    </script>
</body>
</html>
